#clustering
kmeans
mtcars$mpg
dim(mtcars)
str(mtcars)
nrow(mtcars)
ncol(mtcars)
class(mtcars)
?mtcars
summary(mtcars)
df=mtcars
df
head(df)
df$cyl=factor(df$cyl)
str(df)
model3=kmeans(mtcars$mpg,centers=3)
model3
model3$cluster
cbind(mtcars$mpg,model3$cluster)
model3$centers
model4=kmeans(mtcars[,c('mpg','wt')],centers=3)
model4
model4$cluster
cbind(mtcars[,c('mpg','wt')],model4$cluster)
model4$centers
df2=cbind(mtcars[,c('mpg','wt')],cluster2=model4$cluster)
head(df2)
library(dplyr)
df2%>%arrange(cluster2)


df=mtcars
df
